--- 
Dataset: 
  cls: "DatasetVTI"
  args: 
    root_dir: "/Users/salimkhazem/Workspace/phd_thesis/dataset_vti" 
    resize: 256 

Data: 
  Batch_size: 32 
  Shuffle: True 

Model: 
  Name: "ContourVTI" 

Loss: 
  Name: "BCEWithLogitsLoss" 

Optimizer:
  Name: "Adam"
  lr: 0.001

Training: 
  Epochs: 50 
  SEED: 42 
  LR: 0.001
  Multi_GPU: False 

