--- 
Dataset: 
  cls: "DatasetVTI"
  args: 
    root_dir: "/mnt/WoodSeer/Slicing" 
    validation_split: 0.2
    resize: 256 

Data: 
  Batch_size: 32 
  Shuffle: True 

Model: 
  Name: "UNet" 
  args: 
    in_channels: 1
    nb_classes: 1

Loss: 
  Name: "BCEWithLogitsLoss" 

Optimizer:
  Name: "Adam"
  lr: 0.001

Training: 
  Epochs: 50 
  SEED: 42 
  LR: 0.001
  Multi_GPU: False 

