--- 
Dataset: 
  cls: "DatasetVTI"
  args: 
    root_dir: "/mnt/WoodSeer/Slicing" 
    validation_split: 0.2
    resize: 256 

Data: 
  Batch_size: 128 
  Shuffle: False 

Model: 
  Name: "UNet" 
  args: 
    in_channels: 1
    nb_classes: 1

Loss: 
  Name: "BCEWithLogitsLoss" 

Optimizer:
  Name: "Adam"
  lr: 0.001

Training: 
  Epochs: 50 
  SEED: 42 
  LR: 0.001
  Clip_grad_norm: 1
  Multi_GPU: True 
  Checkpoint:
    Resume: False
    Date: "20240709"
    Time: "13h37min40s"
